### ISSUE TITLE
3.1.0 can no longer open terminals

### ISSUE THREAD

**Issue by pcause** [polyipseity/obsidian-terminal#10]
Installed 3.1.0.  My 3.0 terminals worked without.  Turned on the open in new tab.  Checked my 2 profiles and all looked good/the same.  When I open a terminal I now get an error:

The filename, directory name, or volume label syntax is incorrect.

Here is the console error:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\_pswindows.py", line 688, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\_pswindows.py", line 942, in create_time
    user, system, created = cext.proc_times(self.pid)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] assume no such process (originated from OpenProcess -> ERROR_INVALID_PARAMETER)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\__init__.py", line 361, in _init
    self.create_time()
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\__init__.py", line 714, in create_time
    self._create_time = self._proc.create_time()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\_pswindows.py", line 690, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: process no longer exists (pid=17628)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 195, in <module>
  File "<string>", line 28, in main
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\__init__.py", line 332, in __init__
    self._init(pid)
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=17628)

eval @ plugin:terminal:209

**Comment by pcause** [comment]
OK, found out that I could use the new check button and the python path was now wrong for some reason.  You might emphasize/point out to use that test.
